### ISSUE TITLE
Error when build ViSP and UsTK using VS2015 in windows

### ISSUE THREAD

**Issue by LJFking** [lagadic/ustk#31]
When I build ViSP and UsTK using VS 2015 in windows 7, there are a lot of building errors as follows:

LNK1104	cannot open“..\..\x64\vc14\lib\Debug\visp_ustk_template_tracking310d.lib”.

It seems that visp_ustk_template_tracking310d.lib is not generated. I tried several times and cannot figure out where the problem is. Could you give some advice? Thanks.

**Comment by fspindle** [comment]
Can you add the build log

**Comment by fspindle** [comment]
Do you fix the issue ?

**Comment by fspindle** [comment]
Reopen if needed

**Comment by LJFking** [comment]
Thank you for your reply. I tried it in Ubuntu and succeed. As for in Windows, my VS is in Chinese, I will add the english building log soon.
